### PR TITLE
Feat: Add JSON & YAML outputs for images

### PR DESCRIPTION
**Pull request by suryaval**
# Adds support for generating YAML & JSON outputs for images

### Helm Charts

> helm search repo nginx-stable/nginx-ingress

```
NAME                            CHART VERSION   APP VERSION     DESCRIPTION             
nginx-stable/nginx-ingress      0.18.0          3.2.0           NGINX Ingress Controller
```
> helm pull nginx-stable/nginx-ingress

### Helm Decomposer Outputs

```
helm-decomposer -chart nginx-ingress/ -i -j -y

Loading Helm Chart "nginx-ingress/"...

--- Searching images in K8S manifests ---

Image found in nginx-ingress/templates/controller-deployment.yaml...
nginx/nginx-ingress:3.2.0

--- List of unique Docker images in the Helm Chart ---

→ nginx/nginx-ingress:3.2.0

--- Building Tree for the Helm Chart "nginx-ingress" ---

╴ nginx-ingress
```

#### images.json

```
{"images":["nginx/nginx-ingress:3.2.0"]}
```

#### images.yaml

```
images:
    - nginx/nginx-ingress:3.2.0
```

### CODE REVIEW

**Comment by jkosik** [comment]
@suryaval, thank you for your effort. Feature seems very useful. Since new flags are dependent on "-i" flag. Could you merge new flags with "-i", resulting in "-iy" and "-ij" and removing "-i" completely? It could be more user-friendly when need for "-i" is overlook.

While there will be more output files,  I suggest also:
-	flagOutputFile := flag.Bool("o", false, "Write output to helm-decomposer-output.md. (default \"false\")")
+	flagOutputFile := flag.Bool("o", false, "Write chart tree to helm-decomposer-output.md. (default \"false\")")

**Comment by suryaval** [comment]
@jkosik Thanks for reviewing my PR, I will incorporate the changes suggested and add to the current Pull Request:
- Remove flag `-i`, add flags `-iy` & `-ij`
- Add chart tree, images list output to markdown when `-o` is specified

**Comment by jkosik** [comment]
@suryaval  thank you for accepting proposal with -iy and -ij. Regarding -o, I am not sure about putting json or yaml image list next to the tree in MD file while still allowing having them in a separate files (not linear and may be complicated from user perspective).

The initial logic and core feature was to provide tree decomposition in MD file. 

I see two approaches.
1. Keeping -ij and -iy and sending results to separate files (your initial idea) and keeping -o only for tree generation (we can discuss output file renaming and rewording help a bit)
2. Keeping just -o and -i and having just single output MD file with embedded json and yaml image list inside (your last idea)

What are your thoughts and preference on this?

**Comment by suryaval** [comment]
Thanks for detailing the approaches. I will opt for (1)

Use-Cases for (1):
- With serialized output format(YAML&JSON), incorporate Helm-Decomposer in DevSecOps pipelines to scan all images part of helm chart for any vulnerabilities
- With serialized output format(YAML&JSON), incorporate Helm-Decomposer in CI pipelines to promote images from pre-prod container registry to prod container registry

With (1), `-o` can be used only for tree generation and discuss later about preserving the helm-decomposer output

**Comment by suryaval** [comment]
### Validations for: Deprecate -i, add -ij & -iy

#### JSON

```
./helm-decomposer -chart nginx-ingress/ -ij

Loading Helm Chart "nginx-ingress/"...

--- Searching images in K8S manifests ---

Image found in nginx-ingress/templates/controller-deployment.yaml...
nginx/nginx-ingress:3.2.0

--- List of unique Docker images in the Helm Chart ---

→ nginx/nginx-ingress:3.2.0

--- Generating image list as JSON ---
--- File saved to images.json ---
--- Building Tree for the Helm Chart "nginx-ingress" ---

╴ nginx-ingress
```

#### YAML

```
./helm-decomposer -chart nginx-ingress/ -iy

Loading Helm Chart "nginx-ingress/"...

--- Searching images in K8S manifests ---

Image found in nginx-ingress/templates/controller-deployment.yaml...
nginx/nginx-ingress:3.2.0

--- List of unique Docker images in the Helm Chart ---

→ nginx/nginx-ingress:3.2.0

--- Generating image list as YAML ---
--- File saved to images.yaml ---
--- Building Tree for the Helm Chart "nginx-ingress" ---

╴ nginx-ingress
```

**Comment by jkosik** [comment]
@suryaval thank you for contribution. I will update readme video as well soon to match new features.

**Pull request merged**
